# Generated by Django 3.1.7 on 2023-06-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('año', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
